version: '3.3'
services:
  app:
    image: homeautomator/web
    build: .
    entrypoint: ./entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
